apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sudheer-v/argo-cd-demo1.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
